version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_clerk_auth
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    environment:
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_JWT_VERIFICATION_KEY=${CLERK_JWT_VERIFICATION_KEY}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/clerk_auth}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-true}
    depends_on:
      - db
      - redis
    networks:
      - clerk_network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: fastapi_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clerk_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - clerk_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fastapi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - clerk_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fastapi_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - clerk_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  clerk_network:
    driver: bridge